#!/usr/bin/env bash
# File transfer to server using scp
# FILE_PATH=$1, SERVER_IP=$2, USERNAME=$3, SSH_KEY=$

if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
