#!/usr/bin/env bash
# Stops the process created by the script in Task 4 without using kill

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
    echo "pkill PID $pid"
    pkill -P "$pid"
else
    echo "No matching process found"
fi
