#!/usr/bin/env bash

# Create a backup of the original hosts file in the user's home directory
cp /etc/hosts ~/hosts.new

# Update the copy with the new IP addresses for localhost and facebook.com
echo "127.0.0.2        localhost" > ~/hosts.new
echo "8.8.8.8             facebook.com" >> ~/hosts.new

# Overwrite the original hosts file with the updated copy
cp -f ~/hosts.new /etc/hosts
